# 
# Travis CI configuration
#
# https://travis-ci.org/malte70/OSDetect
#

language: python

python:
    - "3.9"
    - "3.11"
    - "3.13"
    - "nightly"

branches:
    only:
        - master

install:
    - pip install .

script:
    - pytest
    - python -m OSDetect

