# 
# Travis CI configuration
#
# https://travis-ci.org/malte70/OSDetect
#

language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "nightly"

branches:
    only:
        - master

install:
    - python setup.py install

script:
    - pytest
    - python -m OSDetect

