title: OSDetect
description: Simple operating system detection method for Python
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
  - jekyll-analytics

jekyll_analytics:
  Piwik:
    url: app.ancistrus.de/piwik
    siteId: "3"
